# Generated by Django 4.2.5 on 2023-10-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("mensagem", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_do_pet", models.CharField(max_length=150)),
                ("telefone", models.CharField(max_length=15)),
                ("data", models.DateField()),
                ("mensagem", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
