# Generated by Django 4.2.5 on 2023-12-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("nome_do_pet", models.CharField(max_length=150)),
                ("data", models.DateField()),
                ("observacoes", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
