# Generated by Django 4.2.5 on 2023-12-21 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_categoria_pet"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="categoria_pet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.pet",
            ),
        ),
    ]
