# Generated by Django 4.2.5 on 2024-01-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_remove_reserva_categoria_pet_reserva_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="data",
            field=models.DateField(max_length=10),
        ),
    ]
